
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  scraper:
    build:
      context: ./backend/ScraperWorker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379
    restart: on-failure

  api:
    build:
      context: ./backend/QuotesApi
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "5000:80"
    environment:
      - REDIS_CONNECTION=redis:6379

  frontend:
    build:
      context: ./frontend/quotes-app
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "4200:80"